# Generated by Django 2.2 on 2021-11-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20211105_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='comprador',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Vendedor'),
        ),
    ]
